### ISSUE TITLE
NaN values when generating intervals in stream match generator

### ISSUE THREAD

**Issue by kangqiu** [avinashresearch1/CompHENS.jl#64]
Occurs when e.g. a hot utility stream is provided in the stream data but not used. Quick fix is not considering that utility stream. 

[CompHENS_interface_MWE.xlsx](https://github.com/avinashresearch1/CompHENS.jl/files/11430449/CompHENS_interface_MWE.xlsx)

@time using CompHENS
using Plots
using JuMP
using HiGHS
using Test

file_path_xlsx = joinpath(@__DIR__, "CompHENS_interface_MWE.xlsx")
prob = ClassicHENSProblem(file_path_xlsx; ΔT_min = 45.0, verbose = true)
@time solve_minimum_utilities_subproblem!(prob; verbose = true)
model::AbstractModel, overall_network::Dict{String, AbstractSuperstructure}, file_name; digits = 1)
@time solve_minimum_units_subproblem!(prob)
EMAT = 2.5
prob.results_dict[:add_units] = 1
@time generate_stream_matches!(prob, EMAT; digits = 8, verbose  = true)

**Comment by avinashresearch1** [comment]
Fixed by: #65
